name: Update JSON File

# Definindo a execução automática diariamente às 00:00 UTC
on:
    schedule:
        - cron: "0 0 * * *" # Rodar todos os dias à meia-noite (UTC)
    push:
        branchs:
            - main

jobs:
    update-json:
        runs-on: ubuntu-latest # Usando um ambiente Ubuntu

        steps:
            # Fazer o checkout do repositório
            - name: Checkout repository
              uses: actions/checkout@v3

            # Configurando o Python para rodar o script
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12" # Define a versão do Python, ex: 3.9

            # Instalar dependências (se necessário)
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt  # Instalar dependências listadas

            # Rodar o script Python para gerar o arquivo JSON
            - name: Run Python script
              run: |
                  python main.py  # Substituir pelo caminho do seu script

            # Adicionar e comitar o arquivo JSON gerado
            - name: Commit changes
              run: |
                  git config --local user.name "github-actions[bot]"
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git add docs/  # Especificar o caminho do arquivo JSON gerado
                  git commit -m "Automated update of JSON file"
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token automático para autenticação
